-- Active: 1745412174410@@127.0.0.1@3306@dbiykpinec1m8s

USE dbiykpinec1m8s;

CREATE TABLE sim_active_codes (
    simCode TEXT    NOT NULL,
	jobCode TEXT    NOT NULL
);

CREATE TABLE sim_terminals (
    id          INT     AUTO_INCREMENT,
    slug 		TEXT    NOT NULL,
    jobCode 	TEXT    NOT NULL,
    displayName TEXT,
    access 		INT		NOT NULL,
	state 		TEXT    NOT NULL,
	stateData 	INT,
	PRIMARY KEY (id)
);

CREATE TABLE sim_entries (
    id          INT     AUTO_INCREMENT,
    terminal_id INT     NOT NULL,
    icon        ENUM('files','darkweb','cameras','locks','defenses','utilities')
                        NOT NULL,
    path        TEXT    NOT NULL,
    type        TEXT    NOT NULL,
    access      INT,
    modify      INT,
    title       TEXT,
    contents    TEXT,
    state       TEXT,
    previous   TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY (terminal_id)
        REFERENCES sim_terminals(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE users (
    ml_id       INT     NOT NULL UNIQUE,
    userCode    TEXT    NOT NULL,
    charName    TEXT    NOT NULL,
    PRIMARY KEY (ml_id)
);

CREATE TABLE sim_access_logs (
    id          INT     AUTO_INCREMENT,
    terminal_id INT     NOT NULL,
    user_id     INT,
    mask        TEXT,
    reassignee  TEXT,
    state       TEXT    NOT NULL,
    tags        INT,
    PRIMARY KEY (id),
    FOREIGN KEY (terminal_id)
        REFERENCES sim_terminals(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (user_id)
        REFERENCES users(ml_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE cpu_roles (
    id      INT     AUTO_INCREMENT,
    name    TEXT    NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE cpu_functions (
    id          INT     AUTO_INCREMENT,
    name        TEXT    NOT NULL,
    type        TEXT,
    hacking_cat TEXT,
    PRIMARY KEY (id)
);

CREATE TABLE cpu_caviats (
    id          INT     AUTO_INCREMENT,
    ml_name     TEXT,
    displayName TEXT,
    PRIMARY KEY (id)
);

CREATE TABLE ml_functions (
    id          INT     AUTO_INCREMENT,
    ml_id       INT     NOT NULL,
    ml_name     TEXT    NOT NULL,
    `rank`      INT     NOT NULL,
    function_id INT     NOT NULL,
    cav_type    TEXT,
    cav_id      INT,
    role_id     INT,
    tier        INT,
    PRIMARY KEY (id),
    FOREIGN KEY (function_id)
        REFERENCES cpu_functions(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    FOREIGN KEY (role_id)
        REFERENCES cpu_roles(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    FOREIGN KEY (cav_id)
        REFERENCES cpu_caviats(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE user_functions (
    user_id         INT     NOT NULL,
    mlFunction_id   INT     NOT NULL,
    cav_id          TEXT,
    CONSTRAINT userFunction
        PRIMARY KEY (user_id, mlFunction_id),
    FOREIGN KEY (user_id)
        REFERENCES users(ml_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (mlFunction_id)
        REFERENCES ml_functions(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
/*
CREATE TABLE user_selfreport (
    user_id         INT NOT NULL,
    mlFunction_id   INT NOT NULL,
    CONSTRAINT userFunction
        PRIMARY KEY (user_id, mlFunction_id),
    FOREIGN KEY (user_id)
        REFERENCES users(ml_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (mlFunction_id)
        REFERENCES ml_functions(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
*/
CREATE TABLE items (
    id          INT     AUTO_INCREMENT,
    name        TEXT    NOT NULL,
    tier        INT     NOT NULL,
    category    TEXT    NOT NULL,
    radio       TEXT,
    abbr        TEXT    NOT NULL,
    enabled     BOOL    NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE item_effects (
    id          INT     AUTO_INCREMENT,
    item_id     INT     NOT NULL,
    abbr        TEXT,
    use_loc     TEXT    NOT NULL,
    req_type    TEXT,
    requirement TEXT,
    charges     INT,
    per_type    TEXT,
    notes       TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY (item_id)
        REFERENCES items(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE user_items (
    user_id INT NOT NULL,
    item_id INT NOT NULL,
    count   INT,
    FOREIGN KEY (user_id)
        REFERENCES users(ml_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (item_id)
        REFERENCES items(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE item_uses (
    user_id     INT     NOT NULL,
    effect_id   INT     NOT NULL,
    simCode     TEXT    NOT NULL,
    jobCode     TEXT    NOT NULL,
    terminal_id INT     NOT NULL,
    FOREIGN KEY (user_id)
        REFERENCES users(ml_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (effect_id)
        REFERENCES item_effects(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (terminal_id)
        REFERENCES sim_terminals(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE sim_user_actions (
    id          INT         AUTO_INCREMENT,
    time        TIMESTAMP   NOT NULL,
    user_id     INT         NOT NULL,
    target_type TEXT        NOT NULL,
    target_id   INT         NOT NULL,
    action      TEXT        NOT NULL,
    newState    TEXT        NOT NULL,
    cost        INT         NOT NULL,
    global      BOOLEAN     NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id)
        REFERENCES users(ml_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

####################################################################################################

INSERT INTO sim_active_codes
            (simCode, jobCode)
    VALUES  ('MAY25', 'ABC1234');

INSERT INTO cpu_functions
            (name, type, hacking_cat)
    VALUES  ('[UNKNOWN]', 'error', NULL),
            ('Advanced Armor Proficiency', 'collect', NULL),
            ('Advanced Shield Proficiency', 'collect', NULL),
            ('Advanced Weapon Proficiency', 'collect', NULL),
            ('Alarm Sense', 'unique', 'passive'),
            ('Ammo Hound', '', NULL),
            ('Armed to the Teeth', '', NULL),
            ('Backdoor', 'ranked', 'passive'),
            ('Basic Proficiencies', 'collect', NULL),
            ('Bestow', 'multi_charge', NULL),
            ('Bind', '', NULL),
            ('Break', '', NULL),
            ('Brick', 'unique', 'active'),
            ('Button Masher', 'ranked', 'initial'),
            ('Cleanse', 'charges', NULL),
            ('Closer', 'multi_charge', NULL),
            ('Connections', 'multi_charge', NULL),
            ('Contractor', 'multi_charge', NULL),
            ('Craft', 'collect', NULL),
            ('Dark Web Merchant', 'unique', 'passive'),
            ('Dark Web Operator', 'unique', 'passive'),
            ('Daze', '', NULL),
            ('Deceptive', '', NULL),
            ('Dig Dirt', '', NULL),
            ('Disarm', '', NULL),
            ('Disguise', '', NULL),
            ('Dodge', 'multi_charge', NULL),
            ('Durable', '', NULL),
            ('Educator', '', NULL),
            ('Embolden', '', NULL),
            ('Encourage', '', NULL),
            ('Energizing', '', NULL),
            ('Escape', '', NULL),
            ('Escape Binds', '', NULL),
            ('Etiquette', '', NULL),
            ('Experimenter', '', NULL),
            ('Expert Bodyguard', '', NULL),
            ('Explosives', '', NULL),
            ('Fear', '', NULL),
            ('Field Repair', 'ranked', 'repair'),
            ('First Aid', 'ranked', NULL),
            ('Fix Limb', '', NULL),
            ('Forgery', 'ranked', NULL),
            ('Fortify', '', NULL),
            ('Gossiper', '', NULL),
            ('Hacking', 'ranked', 'initial'),
            ('Hometown Hero', '', NULL),
            ('Influential', '', NULL),
            ('Inspire', '', NULL),
            ('Instructor', '', NULL),
            ('Interfere', '', NULL),
            ('Intimidate', '', NULL),
            ('Juggernaut', 'multi_charge', NULL),
            ('Juggernaut, Improved', 'unique', NULL),
            ('Junkyard Jockey', '', NULL),
            ('Knockback', '', NULL),
            ('Know Everyone', '', NULL),
            ('Know Somebody', '', NULL),
            ('Know-It-All', '', NULL),
            ('Knowledge', 'collect', 'passive'),
            ('Leadership', '', NULL),
            ('Living Blockade', '', NULL),
            ('Lock', '', NULL),
            ('Machine Whisperer', '', NULL),
            ('Mask', 'unique', 'initial'),
            ('Master of Pain', '', NULL),
            ('Medic', '', NULL),
            ('Melee Disarm', '', NULL),
            ('Melee Knockback', '', NULL),
            ('Melee Lock', '', NULL),
            ('Melee Root', '', NULL),
            ('Nix', 'multi_charge', NULL),
            ('Outgoing', '', NULL),
            ('Pain', '', NULL),
            ('Patroller', '', NULL),
            ('Pep Talk', '', NULL),
            ('Performance', '', NULL),
            ('Pick Locks', '', NULL),
            ('Pick Pocket', '', NULL),
            ('Ping', 'unique', 'active'),
            ('Plant Traps', '', NULL),
            ('Popular', '', NULL),
            ('Power Break', '', NULL),
            ('Power Disarm', '', NULL),
            ('Power Fear', '', NULL),
            ('Power Knockback', '', NULL),
            ('Power Lock', '', NULL),
            ('Power Pain', '', NULL),
            ('Power Root', '', NULL),
            ('Professional', '', NULL),
            ('Project Consultant', '', NULL),
            ('Project Lead', '', NULL),
            ('Project Manager', '', NULL),
            ('Protective Ward', '', NULL),
            ('Protector', '', NULL),
            ('Rage', 'multi_charge', NULL),
            ('Rage, Improved', 'unique', NULL),
            ('Ranged Break', '', NULL),
            ('Ranged Disarm', '', NULL),
            ('Ranged Knockback', '', NULL),
            ('Ranged Lock', '', NULL),
            ('Rapid Crafting', '', NULL),
            ('Reassign', 'unique', 'active'),
            ('Refresh', '', NULL),
            ('Repair', 'ranked', 'repair'),
            ('Repeat', 'ranked', 'passive'),
            ('Reporter', '', NULL),
            ('Research', '', NULL),
            ('Resilient', '', NULL),
            ('Resist', 'multi_charge', NULL),
            ('Rigged', 'unique', 'active'),
            ('Room Fear', '', NULL),
            ('Room Tech Disarm', '', NULL),
            ('Room Tech Lock', '', NULL),
            ('Room Tech Root', '', NULL),
            ('Root Device', 'unique', 'active'),
            ('Root Exploit', 'unique', 'initial'),
            ('Rumormonger', '', NULL),
            ('Scary', '', NULL),
            ('Scavenge', '', NULL),
            ('Scout', '', NULL),
            ('Shoot First', '', NULL),
            ('Silence', '', NULL),
            ('Siphon Charge', 'unique', 'active'),
            ('Slip', '', NULL),
            ('Slippery Target', '', NULL),
            ('Social Bestow', 'multi_charge', NULL),
            ('Social Cleanse', '', NULL),
            ('Social Refresh', '', NULL),
            ('Socialite', '', NULL),
            ('Stabilize', '', NULL),
            ('Strength', '', NULL),
            ('Supply Chain', '', NULL),
            ('Surgery', '', NULL),
            ('Targeted (Choose)', '', NULL),
            ('Targeted Daze', '', NULL),
            ('Targeted Disarm', '', NULL),
            ('Targeted Fear', '', NULL),
            ('Targeted Pain', '', NULL),
            ('Targeted Social Disarm', '', NULL),
            ('Targeted Social Fear', '', NULL),
            ('Targeted Social Lock', '', NULL),
            ('Targeted Social Silence', '', NULL),
            ('Tight-Lipped', '', NULL),
            ('Tough', 'multi_charge', NULL),
            ('Treacherous', '', NULL),
            ('Under Pressure', '', NULL),
            ('Unstoppable', '', NULL),
            ('Walk It Off', '', NULL),
            ('Wipe Your Tracks', 'unique', 'active');

INSERT INTO cpu_caviats
            (ml_name, displayName)
    VALUES  ('All', 'All'),
            ('Agriculture', 'Agriculture'),
            ('Architecture', 'Architecture'),
            ('Electronics', 'Electronics'),
            ('Explosives  Weapons', 'Explosives &amp; Weapons'),
            ('Hacking  Security Systems', 'Hacking &amp; DigiSec'),
            ('Medicine', 'Medicine'),
            ('Law', 'Law'),
            ('Underworld', 'Underworld'),
            ('CLEC', 'CLEC'),
            ('Debutantalus', 'Debutantalus'),
            ('Fuji Krupp Dynamics', 'Fuji Krupp Dynamics'),
            ('Kruger', 'Kruger'),
            ('LAVI', 'LAVI'),
            ('Muny', 'Muny'),
            ('Ra Energy Unlimited', 'Ra Energy Unlimited'),
            ('ReMed', 'ReMed'),
            ('Nutrigen International', 'Nutrigen International'),
            ('Winton Firearms', 'Winton Firearms'),
            ('Moggers', 'Moggers'),
            ('Golden Triangle', 'Golden Triangle'),
            ('Hovercraft', 'Hovercraft'),
            ('Placeholder', 'Placeholder'),
            ('One-Handed Melee', '1H Melee'),
            ('Two-Handed Melee', '2H Melee'),
            ('One-Handed Ranged', '1H Ranged'),
            ('Two-Handed Ranged', '2H Ranged'),
            ('Armor  Weapons', 'Armor &amp; Weapons'),
            ('Utility', 'Utility'),
            ('Light', 'Light'),
            ('Heavy', 'Heavy'),
            ('Suit', 'Suit'),
            ('Small', 'Small'),
            ('Large', 'Large'),
            ('Random', 'Random'),
            ('Social', 'Social'),
            ('Martial', 'Martial'),
            ('Tech', 'Tech'),
            ('Melee', 'Melee'),
            ('Ranged', 'Ranged'),
            ('Resist', 'Resist'),
            ('Nix', 'Nix'),
            ('Dodge', 'Dodge'),
            ('Pain', 'Pain'),
            ('Break', 'Break'),
            ('Knockback', 'Knockback'),
            ('Fear', 'Fear'),
            ('Tough', 'Tough'),
            ('Daze', 'Daze'),
            ('5s', '5s');

INSERT INTO cpu_roles
            (name)
    VALUES  ('Standard'),
            ('Advocate'),
            ('Anthrack'),
            ('Barrower'),
            ('Bastion'),
            ('Breacher'),
            ('Brute'),
            ('Centurion'),
            ('Crime Boss'),
            ('Dissimulator'),
            ('Investigator'),
            ('Mastermind'),
            ('Officer'),
            ('People&#39;s Champion'),
            ('Polymath'),
            ('Scalpel'),
            ('Scoundrel'),
            ('Slipstream'),
            ('Warden');

INSERT INTO ml_functions
            (ml_id, ml_name, `rank`, function_id, cav_type, cav_id, role_id, tier)
    VALUES  (5, 'Scout I', 1, 121, NULL, NULL, 1, 1),
            (6, 'Repair I', 1, 105, NULL, NULL, 1, 1),
            (7, 'Ammo Hound', 1, 6, NULL, NULL, 1, 2),
            (8, 'Resist', 1, 110, NULL, NULL, 1, 1),
            (9, 'Strength I', 1, 132, NULL, NULL, 1, 1),
            (10, 'Weapon Prof (all)&Armor Prof (all)', 1, 9, 'bound', 1, 1, 1),
            (11, 'Connections (Random)', 1, 17, 'bound', 35, 1, 1),
            (12, 'Contractor (Random)', 1, 18, 'bound', 35, 1, 1),
            (13, 'First Aid & Stabilize', 1, 41, NULL, NULL, 1, 1),
            (13, 'First Aid & Stabilize', 1, 131, NULL, NULL, 1, 1),
            (14, 'Knowledge (choose one) -T1St-', 1, 60, 'choice', NULL, 1, 1),
            (15, 'Pick Locks I', 1, 78, NULL, NULL, 1, 1),
            (16, 'Adv Shield Prof (Small)', 1, 3, 'bound', 33, 1, 2),
            (17, 'Adv Weapon Prof (choose one)', 1, 4, 'choice', NULL, 1, 2),
            (18, 'Bind', 1, 11, NULL, NULL, 1, 2),
            (19, 'Craft (Choose one)', 1, 19, 'choice', NULL, 1, 2),
            (20, 'Influential', 1, 48, NULL, NULL, 1, 2),
            (21, 'Performance', 1, 77, NULL, NULL, 1, 2),
            (22, 'Project Consultant', 1, 91, NULL, NULL, 1, 2),
            (23, 'Scavenge I', 1, 120, NULL, NULL, 1, 2),
            (24, 'Scout I -T2St-', 1, 121, NULL, NULL, 1, 2),
            (25, 'Supply Chain I -ST1-', 1, 133, NULL, NULL, 1, 1),
            (26, 'Professional', 1, 90, NULL, NULL, 1, 1),
            (27, 'Under Pressure', 1, 147, NULL, NULL, 1, 2),
            (28, 'Knowledge (choose one)', 1, 60, 'choice', NULL, 1, 2),
            (29, 'Adv Armor Prof (Light)', 1, 2, 'bound', 30, 1, 3),
            (30, 'Escape Binds I', 1, 34, NULL, NULL, 1, 3),
            (31, 'Explosives', 1, 38, NULL, NULL, 1, 3),
            (32, 'Fix Limb I', 1, 42, NULL, NULL, 1, 3),
            (33, 'Hacking I', 1, 46, NULL, NULL, 1, 3),
            (34, 'Instruction', 1, 50, NULL, NULL, 1, 3),
            (35, 'Knowledge (choose one) -T3St-', 1, 60, 'choice', NULL, 1, 3),
            (36, 'Reporter', 1, 107, NULL, NULL, 1, 3),
            (37, 'Research I', 1, 108, NULL, NULL, 1, 3),
            (38, 'Resilient I', 1, 109, NULL, NULL, 1, 3),
            (39, 'Strength I -T3St-', 1, 132, NULL, NULL, 1, 3),
            (40, 'Tight-Lipped', 1, 144, NULL, NULL, 1, 3),
            (41, 'Adv Shield Prof (Small) -AT1-', 1, 3, 'bound', 33, 2, 1),
            (42, 'Adv Weapon Prof (choose one) -AT1-', 1, 4, 'choice', NULL, 2, 1),
            (43, 'Contractor (Social)', 1, 18, 'bound', 36, 2, 1),
            (44, 'Outgoing I -AT1b-', 1, 73, NULL, NULL, 2, 1),
            (45, 'Performance -AT1b-', 1, 77, NULL, NULL, 2, 1),
            (46, 'Resist (Social)', 1, 110, 'bound', 36, 2, 1),
            (47, 'Resist (Social) -AdT1-', 1, 110, 'bound', 36, 2, 1),
            (48, 'Tough', 1, 145, NULL, NULL, 2, 1),
            (49, 'Connections (Any)', 1, 17, 'bound', 35, 2, 2),
            (50, 'Dig Dirt', 1, 24, NULL, NULL, 2, 2),
            (51, 'Fear', 1, 39, NULL, NULL, 2, 2),
            (52, 'Embolden', 1, 30, NULL, NULL, 2, 2),
            (53, 'Fear -AT2-', 1, 39, NULL, NULL, 2, 2),
            (54, 'Resist -AT2-', 1, 110, NULL, NULL, 2, 2),
            (55, 'Social Bestow Tough', 1, 127, 'bound', 48, 2, 2),
            (56, 'Tight-Lipped & Connections (Social)', 1, 144, NULL, NULL, 2, 2),
            (56, 'Tight-Lipped & Connections (Social)', 1, 17, 'bound', 36, 2, 2),
            (57, 'Bestow Resist', 1, 10, 'bound', 41, 2, 3),
            (58, 'Closer (All)', 1, 16, 'bound', 1, 2, 3),
            (59, 'Etiquette', 1, 35, NULL, NULL, 2, 3),
            (60, 'Hometown Hero', 1, 47, NULL, NULL, 2, 3),
            (61, 'Know Everyone', 1, 57, NULL, NULL, 2, 3),
            (62, 'Nix', 1, 72, NULL, NULL, 2, 3),
            (63, 'Power Fear', 1, 85, NULL, NULL, 2, 3),
            (64, 'Bestow Nix', 1, 10, 'bound', 42, 2, 4),
            (65, 'Connections (Random) -AT4-', 1, 17, 'bound', 35, 2, 4),
            (66, 'Pep Talk', 1, 76, NULL, NULL, 2, 4),
            (67, 'Refresh', 1, 104, NULL, NULL, 2, 4),
            (68, 'Socialite', 1, 130, NULL, NULL, 2, 4),
            (69, 'Targeted Social Fear', 1, 141, NULL, NULL, 2, 4),
            (70, 'Bestow Dodge', 1, 10, 'bound', 43, 2, 5),
            (71, 'Closer (All) & Connections (Random)', 1, 16, 'bound', 1, 2, 5),
            (71, 'Closer (All) & Connections (Random)', 1, 17, 'bound', 35, 2, 5),
            (72, 'Daze', 1, 22, NULL, NULL, 2, 5),
            (73, 'Disguise', 1, 26, NULL, NULL, 2, 5),
            (74, 'Dodge', 1, 27, NULL, NULL, 2, 5),
            (75, 'Fortify I', 1, 44, NULL, NULL, 2, 5),
            (76, 'Bestow Pain', 1, 10, 'bound', 44, 3, 1),
            (77, 'Gossiper', 1, 45, NULL, NULL, 3, 1),
            (78, 'Know Everyone -AT1-', 1, 57, NULL, NULL, 3, 1),
            (79, 'Knowledge (choose one) -AT1-', 1, 60, 'choice', NULL, 3, 1),
            (80, 'Outgoing I -AT1-', 1, 73, NULL, NULL, 3, 1),
            (81, 'Performance -AT1-', 1, 77, NULL, NULL, 3, 1),
            (82, 'Resist (Social) -AT1-', 1, 110, 'bound', 36, 3, 1),
            (83, 'Tight-Lipped -AT1-', 1, 144, NULL, NULL, 3, 1),
            (84, 'Closer (All) -AT2-', 1, 16, 'bound', 1, 3, 2),
            (85, 'Contractor (Random) -AT2-', 1, 18, 'bound', 35, 3, 2),
            (86, 'Dig Dirt -AT2-', 1, 24, NULL, NULL, 3, 2),
            (87, 'Hometown Hero -AT2-', 1, 47, NULL, NULL, 3, 2),
            (88, 'Resist (Social) x2', 1, 110, 'bound', 36, 3, 2),
            (89, 'Social Cleanse', 1, 128, NULL, NULL, 3, 2),
            (90, 'Targeted Social Fear -AT2-', 1, 141, NULL, NULL, 3, 2),
            (91, 'Adv Armor Prof (Light) -AT3-', 1, 2, 'bound', 30, 3, 3),
            (92, 'Connections (Random) -AT3-', 1, 17, 'bound', 35, 3, 3),
            (93, 'Encourage', 1, 31, NULL, NULL, 3, 3),
            (94, 'Nix -AT3-', 1, 72, NULL, NULL, 3, 3),
            (95, 'Pep Talk -A3-', 1, 76, NULL, NULL, 3, 3),
            (96, 'Project Lead', 1, 92, NULL, NULL, 3, 3),
            (97, 'Rumormonger', 1, 118, NULL, NULL, 3, 3),
            (98, 'Contractor (Random) x2', 2, 18, 'bound', 35, 3, 4),
            (99, 'Energizing', 1, 32, NULL, NULL, 3, 4),
            (100, 'Know Somebody', 1, 58, NULL, NULL, 3, 4),
            (101, 'Leadership', 1, 61, NULL, NULL, 3, 4),
            (102, 'Nix -AT4-', 1, 72, NULL, NULL, 3, 4),
            (103, 'Social Refresh', 1, 129, NULL, NULL, 3, 4),
            (104, 'Bestow Nix -AT5-', 1, 10, 'bound', 42, 3, 5),
            (105, 'Closer (All) & Conn (Random) -AT5-', 1, 16, 'bound', 1, 3, 5),
            (105, 'Closer (All) & Conn (Random) -AT5-', 1, 17, 'bound', 35, 3, 5),
            (106, 'Contractor/Connections (Random)', 1, 18, 'bound', 35, 3, 5),
            (106, 'Contractor/Connections (Random)', 1, 17, 'bound', 35, 3, 5),
            (107, 'Dodge -AT5-', 1, 27, NULL, NULL, 3, 5),
            (108, 'Inspire', 1, 49, NULL, NULL, 3, 5),
            (109, 'Social Refresh -AT5-', 1, 129, NULL, NULL, 3, 5),
            (110, 'Adv Shield Prof (Small) -BT1-', 1, 3, 'bound', 33, 5, 1),
            (111, 'Adv Weapon Prof (choose one) -BaT1-', 1, 4, 'choice', NULL, 5, 1),
            (112, 'Closer (Tech) & Protector', 1, 16, 'bound', 38, 5, 1),
            (112, 'Closer (Tech) & Protector', 1, 95, NULL, NULL, 5, 1),
            (113, 'Protector', 1, 95, NULL, NULL, 5, 1),
            (114, 'Protector -BT1-', 1, 95, NULL, NULL, 5, 1),
            (115, 'Repair I -BaT1-', 1, 105, NULL, NULL, 5, 1),
            (116, 'Resist (Melee)', 1, 110, 'bound', 39, 5, 1),
            (117, 'Resist (Ranged)', 1, 110, 'bound', 40, 5, 1),
            (118, 'Adv Shield Prof (Large)', 1, 3, 'bound', 34, 5, 2),
            (119, 'Closer (Tech) & Protector -BT2-', 1, 16, 'bound', 38, 5, 2),
            (119, 'Closer (Tech) & Protector -BT2-', 1, 95, NULL, NULL, 5, 2),
            (120, 'Durable', 1, 28, NULL, NULL, 5, 2),
            (121, 'Hacking I -BT2-', 1, 46, NULL, NULL, 5, 2),
            (122, 'Repair II', 2, 105, NULL, NULL, 5, 2),
            (123, 'Resist -BT2b-', 1, 110, NULL, NULL, 5, 2),
            (124, 'Resist -BT2-', 1, 110, NULL, NULL, 5, 2),
            (125, 'Adv Weapon Prof (choose one) -WT1-', 1, 4, 'choice', NULL, 19, 1),
            (126, 'Closer (Martial)', 1, 16, 'bound', 37, 19, 1),
            (127, 'Connections (Martial)', 1, 17, 'bound', 37, 19, 1),
            (128, 'Durable -WT1-', 1, 28, NULL, NULL, 19, 1),
            (129, 'Interfere', 1, 51, NULL, NULL, 19, 1),
            (130, 'Tough (Melee)', 1, 145, 'bound', 39, 19, 1),
            (131, 'Tough (Ranged)', 1, 145, 'bound', 40, 19, 1),
            (132, 'Adv Armor Prof (Heavy)', 1, 2, 'bound', 31, 19, 2),
            (133, 'Closer (All) -WT2-', 1, 16, 'bound', 1, 19, 2),
            (134, 'Living Blockade', 1, 62, NULL, NULL, 19, 2),
            (135, 'Nix (Ranged)', 1, 72, 'bound', 40, 19, 2),
            (136, 'Contractor (Martial) & Interfere', 1, 18, 'bound', 37, 19, 2),
            (136, 'Contractor (Martial) & Interfere', 1, 51, NULL, NULL, 19, 2),
            (137, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (138, 'Power Pain', 1, 88, NULL, NULL, 19, 2),
            (139, 'Tough (Melee) -WT2-', 1, 145, 'bound', 39, 19, 2),
            (140, 'Closer (Martial) & Interfere', 1, 16, 'bound', 37, 19, 3),
            (140, 'Closer (Martial) & Interfere', 1, 51, NULL, NULL, 19, 3),
            (141, 'Disarm', 1, 25, NULL, NULL, 19, 3),
            (142, 'Fortify I -WT3-', 1, 44, NULL, NULL, 19, 3),
            (143, 'Nix (Martial)', 1, 72, 'bound', 37, 19, 3),
            (144, 'Nix (Melee)', 1, 72, 'bound', 39, 19, 3),
            (145, 'Patroller I -WT3-', 1, 75, NULL, NULL, 19, 3),
            (146, 'Protective Ward', 1, 94, NULL, NULL, 19, 3),
            (147, 'Armed To The Teeth', 1, 7, NULL, NULL, 19, 4),
            (148, 'Break', 1, 12, NULL, NULL, 19, 4),
            (149, 'Dodge -WT4-', 1, 27, NULL, NULL, 19, 4),
            (150, 'Protective Ward, Improved', 1, 94, NULL, NULL, 19, 4),
            (151, 'Resilient I -WT4-', 1, 109, NULL, NULL, 19, 4),
            (152, 'Resist &lt;WT4&gt;', 1, 110, NULL, NULL, 19, 4),
            (153, 'Adv Armor Prof (Suit) & Strength 3', 1, 2, 'bound', 32, 19, 5),
            (153, 'Adv Armor Prof (Suit) & Strength 3', 3, 132, NULL, NULL, 19, 5),
            (154, 'Dodge -WT5-', 1, 27, NULL, NULL, 19, 5),
            (155, 'Expert Bodyguard', 1, 37, NULL, NULL, 19, 5),
            (156, 'Power Knockback', 1, 86, NULL, NULL, 19, 5),
            (157, 'Targeted x2', 2, 1, NULL, NULL, 19, 5),
            (158, 'Unstoppable', 1, 148, NULL, NULL, 19, 5),
            (159, 'Adv Weapon Prof (choose one) -SlT1-', 1, 4, 'choice', NULL, 18, 1),
            (160, 'Closer (Tech)', 1, 16, 'bound', 38, 18, 1),
            (161, 'Contractor (Tech)', 1, 18, 'bound', 38, 18, 1),
            (162, 'Knowledge (choose one) -SlT1-', 1, 60, 'choice', NULL, 18, 1),
            (163, 'Pain', 1, 74, NULL, NULL, 18, 1),
            (164, 'Resist (Ranged) -SlT1-', 1, 110, 'bound', 40, 18, 1),
            (165, 'Scavenge I -SlT1-', 1, 120, NULL, NULL, 18, 1),
            (166, 'Wipe Your Tracks', 1, 150, NULL, NULL, 18, 1),
            (167, 'Armed To The Teeth -SlT2-', 1, 7, NULL, NULL, 18, 2),
            (168, 'Connections (Tech)', 1, 17, 'bound', 38, 18, 2),
            (169, 'Escape', 1, 33, NULL, NULL, 18, 2),
            (170, 'Hacking I -SlT2-', 1, 46, NULL, NULL, 18, 2),
            (171, 'Ranged Disarm', 1, 99, NULL, NULL, 18, 2),
            (172, 'Ranged Lock', 1, 101, NULL, NULL, 18, 2),
            (173, 'Resist &lt;Sl T2&gt;', 1, 110, NULL, NULL, 18, 2),
            (174, 'Dark Web Operator', 1, 21, NULL, NULL, 18, 3),
            (175, 'Deceptive', 1, 23, NULL, NULL, 18, 3),
            (176, 'Disarm -SlT3-', 1, 25, NULL, NULL, 18, 3),
            (177, 'Lock', 1, 63, NULL, NULL, 18, 3),
            (178, 'Nix -SlT3-', 1, 72, NULL, NULL, 18, 3),
            (179, 'Repeat II', 2, 106, NULL, NULL, 18, 3),
            (180, 'Shoot First', 1, 122, NULL, NULL, 18, 3),
            (181, 'Adv Armor Prof (Suit)', 1, 2, 'bound', 32, 18, 4),
            (182, 'Break -SlT4-', 1, 12, NULL, NULL, 18, 4),
            (183, 'Dodge (Ranged)', 1, 27, 'bound', 40, 18, 4),
            (184, 'Mask', 1, 65, NULL, NULL, 18, 4),
            (185, 'Power Lock', 1, 87, NULL, NULL, 18, 4),
            (186, 'Rumormonger -SlT4-', 1, 118, NULL, NULL, 18, 4),
            (187, 'Area Tech Disarm', 1, 113, NULL, NULL, 18, 5),
            (188, 'Area Tech Lock', 1, 114, NULL, NULL, 18, 5),
            (189, 'Connections (Tech) x2 & Contractor', 2, 17, 'bound', 38, 18, 5),
            (189, 'Connections (Tech) x2 & Contractor', 1, 18, 'bound', 38, 18, 5),
            (190, 'Dodge -SlT5-', 1, 27, NULL, NULL, 18, 5),
            (191, 'Hacking II', 2, 46, NULL, NULL, 18, 5),
            (192, 'Root Device', 1, 116, NULL, NULL, 18, 5),
            (193, 'Adv Weapon Prof (choose one) -ScT1-', 1, 4, 'choice', NULL, 17, 1),
            (194, 'Deceptive -ScT1-', 1, 23, NULL, NULL, 17, 1),
            (195, 'Escape -ScT1-', 1, 33, NULL, NULL, 17, 1),
            (196, 'Melee Disarm', 1, 68, NULL, NULL, 17, 1),
            (197, 'Outgoing I', 1, 73, NULL, NULL, 17, 1),
            (198, 'Pick Pocket I', 1, 79, NULL, NULL, 17, 1),
            (199, 'Resist (Social) -ScT1-', 1, 110, 'bound', 36, 17, 1),
            (200, 'Shoot First -ScT1-', 1, 122, NULL, NULL, 17, 1),
            (201, 'Adv Weapon Prof (choose one) -ScT2-', 1, 4, 'choice', NULL, 17, 2),
            (202, 'Connections (Social)', 1, 17, 'bound', 36, 17, 2),
            (203, 'Contractor (Ran.) & Closer (Social)', 1, 18, 'bound', 35, 17, 2),
            (203, 'Contractor (Ran.) & Closer (Social)', 1, 16, 'bound', 36, 17, 2),
            (204, 'Dig Dirt -ScT2-', 1, 24, NULL, NULL, 17, 2),
            (205, 'Know Somebody -ScT2-', 1, 58, NULL, NULL, 17, 2),
            (206, 'Ranged Disarm -ScT2-', 1, 99, NULL, NULL, 17, 2),
            (207, 'Resist &lt;Sc T2&gt;', 1, 110, NULL, NULL, 17, 2),
            (208, 'Connections (Random) -ScT3-', 1, 17, 'bound', 35, 17, 3),
            (209, 'Hometown Hero -T3-', 1, 47, NULL, NULL, 17, 3),
            (210, 'Melee Knockback', 1, 69, NULL, NULL, 17, 3),
            (211, 'Nix (Ranged) -ScT3-', 1, 72, 'bound', 40, 17, 3),
            (212, 'Ranged Knockback', 1, 100, NULL, NULL, 17, 3),
            (213, 'Rumormonger -ScT3-', 1, 118, NULL, NULL, 17, 3),
            (214, 'Slippery Target', 1, 126, NULL, NULL, 17, 3),
            (215, 'Connections (Random) & Popular', 1, 17, 'bound', 35, 17, 4),
            (215, 'Connections (Random) & Popular', 1, 82, NULL, NULL, 17, 4),
            (216, 'Dark Web Operator -ScT4-', 1, 21, NULL, NULL, 17, 4),
            (217, 'Daze -ScT4-', 1, 22, NULL, NULL, 17, 4),
            (218, 'Explosives -ScT4-', 1, 38, NULL, NULL, 17, 4),
            (219, 'Knockback', 1, 56, NULL, NULL, 17, 4),
            (220, 'Nix (Melee) -ScT4-', 1, 72, 'bound', 39, 17, 4),
            (221, 'Daze -ScT5-', 1, 22, NULL, NULL, 17, 5),
            (222, 'Disguise -ScT5-', 1, 26, NULL, NULL, 17, 5),
            (223, 'Dodge -ScT5-', 1, 27, NULL, NULL, 17, 5),
            (224, 'Targeted Disarm', 1, 137, NULL, NULL, 17, 5),
            (225, 'Targeted Social Disarm', 1, 140, NULL, NULL, 17, 5),
            (226, 'Treacherous', 1, 146, NULL, NULL, 17, 5),
            (227, 'Bestow Pain -PT1-', 1, 10, 'bound', 44, 15, 1),
            (228, 'Craft (Choose one) -PT1-', 1, 19, 'choice', NULL, 15, 1),
            (229, 'Knowledge (choose one) -PT1-', 1, 60, 'choice', NULL, 15, 1),
            (230, 'Professional -PT1-', 1, 90, NULL, NULL, 15, 1),
            (231, 'Project Consultant -T1-', 1, 91, NULL, NULL, 15, 1),
            (232, 'Research I -PT1-', 1, 108, NULL, NULL, 15, 1),
            (233, 'Scavenge I -PT1-', 1, 120, NULL, NULL, 15, 1),
            (234, 'Supply Chain I -PT1-', 1, 133, NULL, NULL, 15, 1),
            (235, 'Craft (Choose one) -PT2-', 1, 19, 'choice', NULL, 15, 2),
            (236, 'Instruction -PT2-', 1, 50, NULL, NULL, 15, 2),
            (237, 'Know-It-All', 1, 59, NULL, NULL, 15, 2),
            (238, 'Knowledge (choose one) -PT2-', 1, 60, 'choice', NULL, 15, 2),
            (239, 'Reporter -PT2-', 1, 107, NULL, NULL, 15, 2),
            (240, 'Research I -PT2-', 1, 108, NULL, NULL, 15, 2),
            (241, 'Resist (Ranged) -PT2-', 1, 110, 'bound', 40, 15, 2),
            (242, 'Cleanse', 1, 15, NULL, NULL, 15, 3),
            (243, 'Dark Web Merchant', 1, 20, NULL, NULL, 15, 3),
            (244, 'Forgery', 1, 43, NULL, NULL, 15, 3),
            (245, 'Nix -PT3-', 1, 72, NULL, NULL, 15, 3),
            (246, 'Rapid Crafting', 1, 102, NULL, NULL, 15, 3),
            (247, 'Resist &lt;P T3&gt;', 1, 110, NULL, NULL, 15, 3),
            (248, 'Under Pressure -PT3-', 1, 147, NULL, NULL, 15, 3),
            (249, 'Adv Armor Prof (Suit) -PT4-', 1, 2, 'bound', 32, 15, 4),
            (250, 'Bestow Break', 1, 10, 'bound', 45, 15, 4),
            (251, 'Bestow Knockback', 1, 10, 'bound', 46, 15, 4),
            (252, 'Educator', 1, 29, NULL, NULL, 15, 4),
            (253, 'Junkyard Jockey', 1, 55, NULL, NULL, 15, 4),
            (254, 'Refresh -PT4-', 1, 104, NULL, NULL, 15, 4),
            (255, 'Cleanse x2', 2, 15, NULL, NULL, 15, 5),
            (256, 'Dodge -PT5-', 1, 27, NULL, NULL, 15, 5),
            (257, 'Experimenter', 1, 36, NULL, NULL, 15, 5),
            (258, 'Machine Whisperer', 1, 64, NULL, NULL, 15, 5),
            (259, 'Project Manager', 1, 93, NULL, NULL, 15, 5),
            (260, 'Surgery', 1, 134, NULL, NULL, 15, 5),
            (261, 'Adv Weapon Prof (choose one) -OT1-', 1, 4, 'choice', NULL, 13, 1),
            (262, 'Craft (Choose one) -OT1-', 1, 19, 'choice', NULL, 13, 1),
            (263, 'Fix Limb I -OT1-', 1, 42, NULL, NULL, 13, 1),
            (264, 'Knowledge (choose one) -OT1-', 1, 60, 'choice', NULL, 13, 1),
            (265, 'Professional -OT1-', 1, 90, NULL, NULL, 13, 1),
            (266, 'Targeted Social Silence', 1, 143, NULL, NULL, 13, 1),
            (267, 'Tough (Ranged) -OT1-', 1, 145, 'bound', 40, 13, 1),
            (268, 'Under Pressure -OT1-', 1, 147, NULL, NULL, 13, 1),
            (269, 'Armed To The Teeth -OT2-', 1, 7, NULL, NULL, 13, 2),
            (270, 'Bestow Fear', 1, 10, 'bound', 47, 13, 2),
            (271, 'Bestow Tough', 1, 10, 'bound', 48, 13, 2),
            (272, 'Know Everyone -OT2-', 1, 57, NULL, NULL, 13, 2),
            (273, 'Medic', 1, 67, NULL, NULL, 13, 2),
            (274, 'Nix (Ranged) -OT2-', 1, 72, 'bound', 40, 13, 2),
            (275, 'Patroller I', 1, 75, NULL, NULL, 13, 2),
            (276, 'Adv Armor Prof (Heavy) -OT3-', 1, 2, 'bound', 31, 13, 3),
            (277, 'Cleanse -OT3-', 1, 15, NULL, NULL, 13, 3),
            (278, 'Knowledge (choose one) -OT3-', 1, 60, 'choice', NULL, 13, 3),
            (279, 'Nix -OT3-', 1, 72, NULL, NULL, 13, 3),
            (280, 'Project Lead -OT3-', 1, 92, NULL, NULL, 13, 3),
            (281, 'Resist &lt;O T3&gt;', 1, 110, NULL, NULL, 13, 3),
            (282, 'Walk It Off', 1, 149, NULL, NULL, 13, 3),
            (283, 'Bestow Break -OT4-', 1, 10, 'bound', 45, 13, 4),
            (284, 'Bestow Daze', 1, 10, 'bound', 49, 13, 4),
            (285, 'Bestow Daze -OT4-', 1, 10, 'bound', 49, 13, 4),
            (286, 'Cleanse -OT4-', 1, 15, NULL, NULL, 13, 4),
            (287, 'Hometown Hero -OT4-', 1, 47, NULL, NULL, 13, 4),
            (288, 'Leadership -OT4-', 1, 61, NULL, NULL, 13, 4),
            (289, 'Closer (All) & Conn (Random) -OT5-', 1, 16, 'bound', 1, 13, 5),
            (289, 'Closer (All) & Conn (Random) -OT5-', 1, 17, 'bound', 35, 13, 5),
            (290, 'Dodge -OT5-', 1, 27, NULL, NULL, 13, 5),
            (291, 'Know Somebody -OT5-', 1, 58, NULL, NULL, 13, 5),
            (292, 'Refresh -OT5-', 1, 104, NULL, NULL, 13, 5),
            (293, 'Surgery -OT5-', 1, 134, NULL, NULL, 13, 5),
            (294, 'Targeted Daze', 1, 136, NULL, NULL, 13, 5),
            (295, 'Adv Armor Prof (Suit) -BT3-', 1, 2, 'bound', 32, 5, 3),
            (296, 'Armed To The Teeth -BT3-', 1, 7, NULL, NULL, 5, 3),
            (297, 'Dark Web Operator -BT3-', 1, 21, NULL, NULL, 5, 3),
            (298, 'Lock -BT3-', 1, 63, NULL, NULL, 5, 3),
            (299, 'Nix -BaT3-', 1, 72, NULL, NULL, 5, 3),
            (300, 'Patroller I -BT3-', 1, 75, NULL, NULL, 5, 3),
            (301, 'Tough -BT3-', 1, 145, NULL, NULL, 5, 3),
            (302, 'Area Tech Root', 1, 115, NULL, NULL, 5, 4),
            (303, 'Bestow Resist -BT4-', 1, 10, 'bound', 41, 5, 4),
            (304, 'Bestow Resist -B2T4-', 1, 10, 'bound', 41, 5, 4),
            (305, 'Connections (Tech) x2', 2, 17, 'bound', 38, 5, 4),
            (306, 'Fortify I -BT4-', 1, 44, NULL, NULL, 5, 4),
            (307, 'Hacking II -BT4-', 2, 46, NULL, NULL, 5, 4),
            (308, 'Area Tech Lock -BT5-', 1, 114, NULL, NULL, 5, 5),
            (309, 'Dodge -BT5-', 1, 27, NULL, NULL, 5, 5),
            (310, 'Expert Bodyguard -BT5-', 1, 37, NULL, NULL, 5, 5),
            (311, 'Reassign', 1, 103, NULL, NULL, 5, 5),
            (312, 'Resilient 1 & Tough', 1, 109, NULL, NULL, 5, 5),
            (312, 'Resilient 1 & Tough', 1, 145, NULL, NULL, 5, 5),
            (313, 'Resist x2', 2, 110, NULL, NULL, 5, 5),
            (314, 'Adv Weapon Prof (choose one) -BrT1-', 1, 4, 'choice', NULL, 6, 1),
            (315, 'Adv Weapon Prof (choose one) -BT1b-', 1, 4, 'choice', NULL, 6, 1),
            (316, 'Armed To The Teeth -BT1-', 1, 7, NULL, NULL, 6, 1),
            (317, 'Bind -BrT1-', 1, 11, NULL, NULL, 6, 1),
            (318, 'Closer (Martial) -BT1-', 1, 16, 'bound', 37, 6, 1),
            (319, 'Pain -BT1-', 1, 74, NULL, NULL, 6, 1),
            (320, 'Scavenge I -BT1-', 1, 120, NULL, NULL, 6, 1),
            (321, 'Tough (Ranged) -BT1-', 1, 145, 'bound', 40, 6, 1),
            (322, 'Alarm Sense', 1, 5, NULL, NULL, 12, 1),
            (323, 'Dig Dirt -MT1-', 1, 24, NULL, NULL, 12, 1),
            (324, 'Escape Binds I -M1-', 1, 34, NULL, NULL, 12, 1),
            (325, 'Forgery -MT1-', 1, 43, NULL, NULL, 12, 1),
            (326, 'Outgoing I -MT1-', 1, 73, NULL, NULL, 12, 1),
            (327, 'Research I -MT1-', 1, 108, NULL, NULL, 12, 1),
            (328, 'Resist (Social) -MT1-', 1, 110, 'bound', 36, 12, 1),
            (329, 'Silence', 1, 123, NULL, NULL, 12, 1),
            (330, 'Deceptive -MT2-', 1, 23, NULL, NULL, 12, 2),
            (331, 'Dig Dirt & Gossiper', 1, 24, NULL, NULL, 12, 2),
            (331, 'Dig Dirt & Gossiper', 1, 45, NULL, NULL, 12, 2),
            (332, 'Escape -MT2-', 1, 33, NULL, NULL, 12, 2),
            (333, 'Resist (Social) x2 -MT2-', 2, 110, 'bound', 36, 12, 2),
            (334, 'Scary', 1, 119, NULL, NULL, 12, 2),
            (335, 'Scout II', 2, 121, NULL, NULL, 12, 2),
            (336, 'Slippery Target -MT2-', 1, 126, NULL, NULL, 12, 2),
            (337, 'Intimidate', 1, 52, NULL, NULL, 12, 3),
            (338, 'Knowledge (choose one) -MT3-', 1, 60, 'choice', NULL, 12, 3),
            (339, 'Nix -MT3b-', 1, 72, NULL, NULL, 12, 3),
            (340, 'Nix -MT3-', 1, 72, NULL, NULL, 12, 3),
            (341, 'Power Fear -MT3-', 1, 85, NULL, NULL, 12, 3),
            (342, 'Rumormonger -MT3-', 1, 118, NULL, NULL, 12, 3),
            (343, 'Targeted Social Silence -MT3-', 1, 143, NULL, NULL, 12, 3),
            (344, 'Leadership -MT4-', 1, 61, NULL, NULL, 12, 4),
            (345, 'Power Lock -MT4-', 1, 87, NULL, NULL, 12, 4),
            (346, 'Targeted Social Fear -MT4-', 1, 141, NULL, NULL, 12, 4),
            (347, 'Targeted Social Fear -MT4b-', 1, 141, NULL, NULL, 12, 4),
            (348, 'Targeted Social Silence -MT4-', 1, 143, NULL, NULL, 12, 4),
            (349, 'Treacherous -MT4-', 1, 146, NULL, NULL, 12, 4),
            (350, 'Dodge -MT5-', 1, 27, NULL, NULL, 12, 5),
            (351, 'Social Refresh -MT5-', 1, 129, NULL, NULL, 12, 5),
            (352, 'Socialite -MT5-', 1, 130, NULL, NULL, 12, 5),
            (353, 'Targeted Social Lock', 1, 142, NULL, NULL, 12, 5),
            (354, 'Targeted Social Lock -MT5-', 1, 142, NULL, NULL, 12, 5),
            (355, 'Targeted Social Silence -MT5-', 1, 143, NULL, NULL, 12, 5),
            (356, 'Alarm Sense -DT1-', 1, 5, NULL, NULL, 10, 1),
            (357, 'Escape Binds I -DT1-', 1, 34, NULL, NULL, 10, 1),
            (358, 'Hacking I -DT1-', 1, 46, NULL, NULL, 10, 1),
            (359, 'Lock -DT1-', 1, 63, NULL, NULL, 10, 1),
            (360, 'Pick Locks I -DT1-', 1, 78, NULL, NULL, 10, 1),
            (361, 'Scavenge I -DT1-', 1, 120, NULL, NULL, 10, 1),
            (362, 'Scavenge I -DT1b-', 1, 120, NULL, NULL, 10, 1),
            (363, 'Silence -DT1-', 1, 123, NULL, NULL, 10, 1),
            (364, 'Backdoor I', 1, 8, NULL, NULL, 10, 2),
            (365, 'Hacking I -DT2-', 1, 46, NULL, NULL, 10, 2),
            (366, 'Pick Pocket I -DT2-', 1, 79, NULL, NULL, 10, 2),
            (367, 'Plant Traps', 1, 81, NULL, NULL, 10, 2),
            (368, 'Repeat I', 1, 106, NULL, NULL, 10, 2),
            (369, 'Resist (Ranged) -DT2-', 1, 110, 'bound', 40, 10, 2),
            (370, 'Supply Chain I', 1, 133, NULL, NULL, 10, 2),
            (371, 'Escape -DT3-', 1, 33, NULL, NULL, 10, 3),
            (372, 'Knowledge (choose one) -DT3-', 1, 60, 'choice', NULL, 10, 3),
            (373, 'Nix -DT3-', 1, 72, NULL, NULL, 10, 3),
            (374, 'Resist &lt;D T3&gt;', 1, 110, NULL, NULL, 10, 3),
            (375, 'Scout III', 3, 121, NULL, NULL, 10, 3),
            (376, 'Slippery Target -DT3-', 1, 126, NULL, NULL, 10, 3),
            (377, 'Wipe Your Tracks -DT3-', 1, 150, NULL, NULL, 10, 3),
            (378, 'Adv Armor Prof (Suit) -DT4-', 1, 2, 'bound', 32, 10, 4),
            (379, 'Backdoor I -DT4-', 1, 8, NULL, NULL, 10, 4),
            (380, 'Brick', 1, 13, NULL, NULL, 10, 4),
            (381, 'Junkyard Jockey -DT4-', 1, 55, NULL, NULL, 10, 4),
            (382, 'Reassign -DT4-', 1, 103, NULL, NULL, 10, 4),
            (383, 'Area Tech Lock -DT5-', 1, 114, NULL, NULL, 10, 5),
            (384, 'Dodge -DT5-', 1, 27, NULL, NULL, 10, 5),
            (385, 'Experimenter -DT5-', 1, 36, NULL, NULL, 10, 5),
            (386, 'Rigged', 1, 111, NULL, NULL, 10, 5),
            (387, 'Root Exploit', 1, 117, NULL, NULL, 10, 5),
            (388, 'Treacherous -DT5-', 1, 146, NULL, NULL, 10, 5),
            (389, 'Adv Weapon Prof (choose one) -BT1-', 1, 4, 'choice', NULL, 7, 1),
            (390, 'Bind -BT1-', 1, 11, NULL, NULL, 7, 1),
            (391, 'Melee Root', 1, 71, NULL, NULL, 7, 1),
            (392, 'Scary -BT1-', 1, 119, NULL, NULL, 7, 1),
            (393, 'Scavenge I -BrT1-', 1, 120, NULL, NULL, 7, 1),
            (394, 'Scout I -BT1-', 1, 121, NULL, NULL, 7, 1),
            (395, 'Silence -BT1-', 1, 123, NULL, NULL, 7, 1),
            (396, 'Tough (Melee) -BT1-', 1, 145, 'bound', 39, 7, 1),
            (397, 'Armed To The Teeth -BT2-', 1, 7, NULL, NULL, 7, 2),
            (398, 'Fear -BT2-', 1, 39, NULL, NULL, 7, 2),
            (399, 'Melee Lock', 1, 70, NULL, NULL, 7, 2),
            (400, 'Nix (Melee) -BrT2-', 1, 72, 'bound', 39, 7, 2),
            (401, 'Patroller I -BrT2-', 1, 75, NULL, NULL, 7, 2),
            (402, 'Scout II -BrT2-', 2, 121, NULL, NULL, 7, 2),
            (403, 'Tough -BrT2-', 1, 145, NULL, NULL, 7, 2),
            (404, 'Fear & Silence', 1, 39, NULL, NULL, 7, 3),
            (404, 'Fear & Silence', 1, 123, NULL, NULL, 7, 3),
            (405, 'Indomitable (5s)', 1, 96, 'bound', 50, 7, 3),
            (406, 'Nix -BT3-', 1, 72, NULL, NULL, 7, 3),
            (407, 'Plant Traps -BT3-', 1, 81, NULL, NULL, 7, 3),
            (408, 'Power Root', 1, 89, NULL, NULL, 7, 3),
            (409, 'Resist &lt;B T3&gt;', 1, 110, NULL, NULL, 7, 3),
            (410, 'Scavenge I -BT3-', 1, 120, NULL, NULL, 7, 3),
            (411, 'Indomitable (5s) -BT4-', 1, 96, 'bound', 50, 7, 4),
            (412, 'Indomitable, Improved', 1, 97, NULL, NULL, 7, 4),
            (413, 'Junkyard Jockey -BT4-', 1, 55, NULL, NULL, 7, 4),
            (414, 'Power Break', 1, 83, NULL, NULL, 7, 4),
            (415, 'Power Break -BT4-', 1, 83, NULL, NULL, 7, 4),
            (416, 'Power Pain x2', 2, 88, NULL, NULL, 7, 4),
            (417, 'Dodge (Ranged) -BT5-', 1, 27, 'bound', 40, 7, 5),
            (418, 'Indomitable (5s) -BT5-', 1, 96, 'bound', 50, 7, 5),
            (419, 'Master of Pain', 1, 66, NULL, NULL, 7, 5),
            (420, 'Targeted Social Fear -BT5-', 1, 141, NULL, NULL, 7, 5),
            (421, 'Targeted Social Lock -BT5-', 1, 142, NULL, NULL, 7, 5),
            (422, 'Treacherous -BT5-', 1, 146, NULL, NULL, 7, 5),
            (423, 'Connections (Martial) -BT2-', 1, 17, 'bound', 37, 6, 2),
            (424, 'Explosives -BT2-', 1, 38, NULL, NULL, 6, 2),
            (425, 'Patroller I -BT2-', 1, 75, NULL, NULL, 6, 2),
            (426, 'Power Pain -BT2-', 1, 88, NULL, NULL, 6, 2),
            (427, 'Ranged Break', 1, 98, NULL, NULL, 6, 2),
            (428, 'Scout I -BT2-', 1, 121, NULL, NULL, 6, 2),
            (429, 'Disarm -BT3-', 1, 25, NULL, NULL, 6, 3),
            (430, 'Durable -BT3-', 1, 28, NULL, NULL, 6, 3),
            (431, 'Nix (Ranged) -BT3-', 1, 72, 'bound', 40, 6, 3),
            (432, 'Resilient I -BT3-', 1, 109, NULL, NULL, 6, 3),
            (433, 'Scary -BT3-', 1, 119, NULL, NULL, 6, 3),
            (434, 'Strength II', 2, 132, NULL, NULL, 6, 3),
            (435, 'Targeted Pain', 1, 139, NULL, NULL, 6, 3),
            (436, 'Break -BT4-', 1, 12, NULL, NULL, 6, 4),
            (437, 'Power Pain x2 -BT4-', 2, 88, NULL, NULL, 6, 4),
            (438, 'Rage (5s)', 1, 53, 'bound', 50, 6, 4),
            (439, 'Rage (5s) -BT4-', 1, 53, 'bound', 50, 6, 4),
            (440, 'Resist &lt;B T4&gt;', 1, 110, NULL, NULL, 6, 4),
            (441, 'Scout II -BT4-', 2, 121, NULL, NULL, 5, 4),
            (442, 'Dodge (Ranged) -BrT5-', 1, 27, 'bound', 40, 6, 5),
            (443, 'Master of Pain -BrT5-', 1, 66, NULL, NULL, 6, 5),
            (444, 'Power Break -BrT5-', 1, 83, NULL, NULL, 6, 5),
            (445, 'Rage (5s) -BrT5-', 1, 53, 'bound', 50, 6, 5),
            (446, 'Rage, Improved', 1, 54, NULL, NULL, 6, 5),
            (447, 'Resilient I & Tough', 1, 109, NULL, NULL, 6, 5),
            (447, 'Resilient I & Tough', 1, 145, NULL, NULL, 6, 5),
            (448, 'Nix (Ranged) -BT2-', 1, 72, 'bound', 40, 6, 2),
            (449, 'Adv Shield Prof (Large) -WT1-', 1, 3, 'bound', 34, 19, 1),
            (450, 'Scout II -BreT4-', 2, 121, NULL, NULL, 6, 4),
            (451, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (452, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (453, 'Alarm Sense -CT1-', -1, 1, NULL, NULL, NULL, NULL),
            (454, 'Hacking I -CT1-', -1, 1, NULL, NULL, NULL, NULL),
            (455, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (456, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (457, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (458, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (459, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (460, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (461, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (462, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (463, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (464, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (465, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (466, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (467, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (468, 'Hacking I -CT3-', -1, 1, NULL, NULL, NULL, NULL),
            (469, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (470, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (471, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (472, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (473, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (474, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (475, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (476, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (477, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (478, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (479, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (480, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (481, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (482, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (483, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (484, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (485, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (486, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (487, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (488, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (489, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (490, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (491, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (492, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (493, 'hidden_skill_purchase_rejection', -1, 1, NULL, NULL, NULL, NULL),
            (494, 'hidden_skill_purchase_rejection', -1, 1, NULL, NULL, NULL, NULL),
            (495, 'hidden_skill_purchase_rejection', -1, 1, NULL, NULL, NULL, NULL),
            (496, 'hidden_skill_purchase_rejection', -1, 1, NULL, NULL, NULL, NULL),
            (498, 'hidden_skill_purchase_rejection', -1, 1, NULL, NULL, NULL, NULL),
            (499, 'hidden_skill_purchase_rejection', -1, 1, NULL, NULL, NULL, NULL),
            (500, 'hidden_skill_purchase_rejection', -1, 1, NULL, NULL, NULL, NULL),
            (501, 'Alarm Sense & Silence', 1, 5, NULL, NULL, 4, 1),
            (501, 'Alarm Sense & Silence', 1, 123, NULL, NULL, 4, 1),
            (502, 'First Aid & Stabilize -BT1-', 1, 41, NULL, NULL, 4, 1),
            (502, 'First Aid & Stabilize -BT1-', 1, 131, NULL, NULL, 4, 1),
            (503, 'Fix Limb I -BwT1-', 1, 42, NULL, NULL, 4, 1),
            (504, 'Medic & Knowledge (Medical)', 1, 67, NULL, NULL, 4, 1),
            (504, 'Medic & Knowledge (Medical)', 1, 60, 'bound', 7, 4, 1),
            (505, 'Pick Locks I -BwT1-', 1, 78, NULL, NULL, 4, 1),
            (506, 'Scout I -BwT1-', 1, 121, NULL, NULL, 4, 1),
            (507, 'Slip -BT1-', 1, 125, NULL, NULL, 4, 1),
            (508, 'Strength II -BT1-', 2, 132, NULL, NULL, 4, 1),
            (509, 'Adv Shield Prof (Small) -BwT1-', 1, 3, 'bound', 33, 4, 2),
            (510, 'Adv Weapon Prof (choose one) -BwT1-', 1, 4, 'choice', NULL, 4, 2),
            (511, 'Craft (Choose one) -BT2-', 1, 19, 'choice', NULL, 4, 2),
            (512, 'Slip -BT2-', 1, 125, NULL, NULL, 4, 2),
            (513, 'Supply Chain I -BwT2-', 1, 133, NULL, NULL, 4, 2),
            (514, 'Surgery -BT2-', 1, 134, NULL, NULL, 4, 2),
            (515, 'Targeted Social Silence -BwT2-', 1, 143, NULL, NULL, 4, 2),
            (516, 'Adv Armor Prof (Light) -BT3-', 1, 2, 'bound', 30, 4, 3),
            (517, 'Dark Web Merchant -BT3-', 1, 20, NULL, NULL, 4, 3),
            (518, 'Instruction -BT3-', 1, 50, NULL, NULL, 4, 3),
            (519, 'Knowledge (choose one) -BT3-', 1, 60, 'choice', NULL, 4, 3),
            (520, 'Research I -BT3-', 1, 108, NULL, NULL, 4, 3),
            (521, 'Scout II -BT3-', 2, 121, NULL, NULL, 4, 3),
            (522, 'Slippery Target -BT3-', 1, 126, NULL, NULL, 4, 3),
            (523, 'Contractor/Connections (Any) -BT4-', 1, 18, 'bound', 35, 4, 4),
            (523, 'Contractor/Connections (Any) -BT4-', 1, 17, 'bound', 35, 4, 4),
            (524, 'Reporter -BT4-', 1, 107, NULL, NULL, 4, 4),
            (525, 'Research I -BT4-', 1, 108, NULL, NULL, 4, 4),
            (526, 'Slip x2', 2, 125, NULL, NULL, 4, 4),
            (527, 'Targeted Social Lock -BT4-', 1, 142, NULL, NULL, 4, 4),
            (528, 'Treacherous -BT4-', 1, 146, NULL, NULL, 4, 4),
            (529, 'Contractor/Connections (Any) -BT5-', 1, 18, 'bound', 35, 4, 5),
            (529, 'Contractor/Connections (Any) -BT5-', 1, 17, 'bound', 35, 4, 5),
            (530, 'Dodge -BwT5-', 1, 27, NULL, NULL, 4, 5),
            (531, 'Educator -BT5-', 1, 29, NULL, NULL, 4, 5),
            (532, 'Experimenter -BT5-', 1, 36, NULL, NULL, 4, 5),
            (533, 'Targeted Social Lock -BwT5-', 1, 142, NULL, NULL, 4, 5),
            (534, 'Treacherous -BwT5-', 1, 146, NULL, NULL, 4, 5),
            (535, 'hidden_skill_purchase_rejection', -1, 1, NULL, NULL, NULL, NULL),
            (536, 'Brutal Path, Tier 1', 0, 1, NULL, NULL, 11, NULL),
            (537, 'Brutal Path, Tier 2', 0, 1, NULL, NULL, 11, NULL),
            (538, 'Brutal Path, Tier 3', 0, 1, NULL, NULL, 11, NULL),
            (539, 'hidden_skill_purchase_rejection', -1, 1, NULL, NULL, NULL, NULL),
            (540, 'Dodge (Ranged) -DT4-', 1, 27, 'bound', 40, 10, 4),
            (541, 'hidden_skill_purchase_rejection', -1, 1, NULL, NULL, NULL, NULL),
            (542, 'hidden_skill_purchase_rejection', -1, 1, NULL, NULL, NULL, NULL),
            (543, 'hidden_skill_purchase_rejection', -1, 1, NULL, NULL, NULL, NULL),
            (544, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL),
            (545, 'hidden_skill_purchase_rejection', -1, 1, NULL, NULL, NULL, NULL),
            (546, 'Shield Path, Tier 1', 0, 1, NULL, NULL, 8, NULL),
            (547, 'Shield Path, Tier 2', 0, 1, NULL, NULL, 8, NULL),
            (548, 'Shield Path, Tier 3', 0, 1, NULL, NULL, 8, NULL),
            (550, 'People&#39;s Champion-R Tier 1', 0, 1, NULL, NULL, 14, NULL),
            (551, 'People&#39;s Champion-R Tier 2', 0, 1, NULL, NULL, 14, NULL),
            (552, 'Sword Path, Tier 1', 0, 1, NULL, NULL, 8, NULL),
            (553, 'Sword Path, Tier 2', 0, 1, NULL, NULL, 8, NULL),
            (554, 'Sword Path, Tier 3', 0, 1, NULL, NULL, 8, NULL),
            (555, 'People&#39;s Champion-R Tier 3', 0, 1, NULL, NULL, 14, NULL),
            (557, 'People&#39;s Champion-V Tier 1', 0, 1, NULL, NULL, 14, NULL),
            (558, 'People&#39;s Champion-V Tier 2', 0, 1, NULL, NULL, 14, NULL),
            (559, 'People&#39;s Champion-V Tier 3', 0, 1, NULL, NULL, 14, NULL),
            (560, 'Kingpin, Tier 1', 0, 1, NULL, NULL, 9, NULL),
            (561, 'Kingpin, Tier 2', 0, 1, NULL, NULL, 9, NULL),
            (562, 'Kingpin, Tier 3', 0, 1, NULL, NULL, 9, NULL),
            (563, 'Puppeteer, Tier 1', 0, 1, NULL, NULL, 9, NULL),
            (564, 'Puppeteer, Tier 2', 0, 1, NULL, NULL, 9, NULL),
            (565, 'Puppeteer, Tier 3', 0, 1, NULL, NULL, 9, NULL),
            (566, 'Cunning, Tier 1', 0, 1, NULL, NULL, 11, NULL),
            (567, 'Cunning, Tier 2', 0, 1, NULL, NULL, 11, NULL),
            (568, 'Cunning, Tier 3', 0, 1, NULL, NULL, 11, NULL),
            (569, 'Adv Shield Prof (pick one) -S1-', 1, 3, 'choice', NULL, 16, 1),
            (570, 'Adv Wep Prof (2HR) -S1-', 1, 4, 'bound', 27, 16, 1),
            (571, 'First Aid & Stabilize -S1-', 1, 41, NULL, NULL, 16, 1),
            (571, 'First Aid & Stabilize -S1-', 1, 131, NULL, NULL, 16, 1),
            (573, 'Fix Limb I -S1-', 1, 42, NULL, NULL, 16, 1),
            (574, 'Medic & Knowledge (Medical) -S1-', 1, 67, NULL, NULL, 16, 1),
            (574, 'Medic & Knowledge (Medical) -S1-', 1, 60, 'bound', 7, 16, 1),
            (575, 'Scout I -S1-', 1, 121, NULL, NULL, 16, 1),
            (576, 'Strength 1 -S1-', 1, 132, NULL, NULL, 16, 1),
            (577, 'Under Pressure -S1-', 1, 147, NULL, NULL, 16, 1),
            (578, 'Adv Armor Prof (Heavy) -S2-', 1, 2, 'bound', 31, 16, 2),
            (579, 'Closer (Martial) -S2-', 1, 16, 'bound', 37, 16, 2),
            (580, 'Fear -S2-', 1, 39, NULL, NULL, 16, 2),
            (581, 'Nix (Ranged) -S2-', 1, 72, 'bound', 40, 16, 2),
            (582, 'Professional -S2-', 1, 90, NULL, NULL, 16, 2),
            (583, 'Resist (Ranged) -S2-', 1, 110, 'bound', 40, 16, 2),
            (584, 'Strength I & Tough (Ranged) -S2-', 1, 132, NULL, NULL, 16, 2),
            (584, 'Strength I & Tough (Ranged) -S2-', 1, 145, 'bound', 40, 16, 2),
            (585, 'Armed to the Teeth -S3-', 1, 7, NULL, NULL, 16, 3),
            (586, 'Explosives -S3-', 1, 38, NULL, NULL, 16, 3),
            (587, 'Patroller -S3-', 1, 75, NULL, NULL, 16, 3),
            (588, 'Power Disarm -S3-', 1, 84, NULL, NULL, 16, 3),
            (589, 'Ranged Break -S3-', 1, 98, NULL, NULL, 16, 3),
            (590, 'Scout 2 -S3-', 2, 121, NULL, NULL, 16, 3),
            (591, 'Targeted Fear -S3-', 1, 138, NULL, NULL, 16, 3),
            (592, 'Cleanse -S4-', 1, 15, NULL, NULL, 16, 4),
            (593, 'Dodge (ranged) -S4-', 1, 27, 'bound', 40, 16, 4),
            (594, 'Interfere & Protector -S4-', 1, 51, NULL, NULL, 16, 4),
            (594, 'Interfere & Protector -S4-', 1, 95, NULL, NULL, 16, 4),
            (595, 'Nix (Ranged) x2  -S4-', 2, 72, 'bound', 40, 16, 4),
            (596, 'Power Disarm -S4-', 1, 84, NULL, NULL, 16, 4),
            (597, 'Surgery -S4-', 1, 134, NULL, NULL, 16, 4),
            (598, 'Area Fear -S5-', 1, 112, NULL, NULL, 16, 5),
            (599, 'Closer (any) x2 -S5-', 2, 16, 'bound', 35, 16, 5),
            (600, 'Dodge -S5-', 1, 27, NULL, NULL, 16, 5),
            (601, 'Expert Bodyguard -S5-', 1, 37, NULL, NULL, 16, 5),
            (602, 'Rage (5s) -S5-', 1, 53, 'bound', 50, 16, 5),
            (603, 'Unstoppable -S5-', 1, 148, NULL, NULL, 16, 5),
            (604, 'skill_category_access_required', -1, 1, NULL, NULL, NULL, NULL);

# 2.0 TEST FUNCTIONS #
INSERT INTO ml_functions
            (ml_id, ml_name, `rank`, function_id, cav_type, cav_id, role_id, tier)
    VALUES  (1000, 'Ping -T1-', 1, 80, NULL, NULL, 1, 1),
            (1001, 'Siphon Charge -T2-', 1, 124, NULL, NULL, 1, 2),
            (1002, 'Button Masher I', 1, 14, NULL, NULL, 15, 3),
            (1003, 'Button Masher II', 2, 14, NULL, NULL, 5, 4),
            (1004, 'Field Repair I', 1, 41, NULL, NULL, 1, 5);
# END TEST FUNCTIONS #

INSERT INTO items
            (name, tier, category, radio, abbr, enabled)
    VALUES  ('Budget Cyberdeck',0,'deck','deck','deck_bud',1),
            ('Budget Remote Access Drive',0,'util',NULL,'brad',1),
            ('Canopic Jar [Magsweep]',0,'impl',NULL,'impl_mags',1),
            ('CLEC Fingers',0,'impl',NULL,'impl_clec',1),
            ('CMM Cocoon',2,'arms',NULL,'cmm',1),
            ('CMM Widow',2,'arms',NULL,'cmm',1),
            ('Copycat',0,'cust',NULL,'copycat',1),
            ('CRD Spider Cyberdeck',1,'deck','deck','deck_crd1',1),
            ('CRD Spider Cyberdeck',2,'deck','deck','deck_crd2',1),
            ('CypherSync Beacon',0,'util',NULL,'beac',1),
            ('DigiPet',0,'util',NULL,'pet_play',1),
            ('Johnny&#39;s Special Touch',1,'deck','deck','deck_jst',1),
            ('MM Console',0,'deck','deck','deck_mm',1),
            ('Nerd&#39;s Safety Glasses',0,'util',NULL,'--',0),
            ('Pocket Hacker',0,'cust','ph','phack0',1),
            ('Pocket Hacker',1,'cust','ph','phack1',1),
            ('Power Glove [Ultra-Hacking 9000]',1,'impl','deck','deck_uh9k',1),
            ('Shimmerstick',0,'cons',NULL,'shim0',1),
            ('Shimmerstick',1,'cons',NULL,'shim1',1),
            ('Vigil',0,'cons',NULL,'vigl0',1),
            ('Vigil',1,'cons',NULL,'vigl1',1);

INSERT INTO item_effects
            (item_id, abbr, use_loc, req_type, requirement, charges, per_type, notes)
    VALUES  (1,'deck_bud','itemTab',NULL,NULL,1,'sim','[DECK] +1 Tag'),
            (2,'brad','before_after','function','Hacking',NULL,NULL,NULL),
            (3,'impl_mags','init',NULL,NULL,1,'sim','Perform Brick Action / Skip Timer'),
            (4,'impl_clec','init',NULL,NULL,1,'sim','+1 Hacking'),
            (5,'cmm_coc','init','function','Slip',1,'scene','+1 Tag'),
            (6,'cmm_wid','init','function','Slip',1,'scene','+1 Tag'),
            (7,'copycat','confirm',NULL,NULL,1,'sim','Skip Action Timer'),
            (8,'deck_crd1','itemTab',NULL,NULL,1,'sim','[DECK] +1 Tag'),
            (9,'deck_crd2','itemTab',NULL,NULL,2,'sim','[DECK] +2 Tags'),
            (10,'beac','auto_init',NULL,NULL,NULL,NULL,'+1 Hacking'),
            (11,'pet_play','itemTab',NULL,NULL,1,'sim','[Nothing except adds active effect]'),
            (11,'pet_use','execute','active_effect','pet_play',1,'scene','Complete Timer'),
            (12,'deck_jst','auto_action',NULL,NULL,NULL,NULL,'Repeat > Access > All Icons > -1 Tag'),
            (13,'deck_mm','itemTab',NULL,NULL,2,'sim','[DECK] +1 Tag'),
            (14,'--','failed_puzzle',NULL,NULL,1,'sim','Re-attempt failed Puzzle'),
            (15,'phack0','itemTab',NULL,NULL,1,'sim','+1 Tag'),
            (16,'phack1','itemTab',NULL,NULL,2,'sim','+1 Tag'),
            (17,'deck_uh9k','auto_init',NULL,NULL,NULL,NULL,'Timer -5s'),
            (18,'shim0','before_after',NULL,NULL,10,'item',NULL),
            (19,'shim1','before_after',NULL,NULL,10,'item',NULL),
            (20,'vigl0','init',NULL,NULL,1,'item',NULL),
            (21,'vigl1','init',NULL,NULL,1,'item',NULL);